chore: added player
hrishikeshpaul/vibey pull request #57
Opened 2021-08-10 04:07 UTC by hrishikeshpaul

2021-08-10 04:21 UTC, s-munro requested changes
Everything is looking pretty solid at first glance, just a bunch of small things relating to imports and comments.  Going to checkout to this branch and test it out in a moment

2021-08-10 04:21 UTC, s-munro commented on vb-be/src/modules/player/player.controller.ts
> +import { PlayerService } from './player.service';
nit: imports

2021-08-10 04:21 UTC, s-munro commented on vb-be/src/modules/player/player.module.ts
> +import { PlayerService } from './player.service';
same here

2021-08-10 04:21 UTC, s-munro commented on vb-fe/src/App.tsx
> +import { Button } from "@chakra-ui/react";
nit: imports

2021-08-10 04:21 UTC, s-munro commented on vb-fe/src/_store/player/PlayerReducer.ts
> +// import { Error } from "app/models/system.model";
nit: remove

2021-08-10 04:21 UTC, s-munro commented on vb-fe/src/core/player/usePlayer.ts
> +import { PlayerConstants } from "_store/player/PlayerTypes";
nit: import

2021-08-10 04:21 UTC, s-munro commented on vb-fe/src/core/player/usePlayer.ts
> +        // play("spotify:album:0Nu5uWgrnNGWWbWfzXPgPI", data.device_id);
comment here

2021-08-12 15:50 UTC, hrishikeshpaul commented
closing this -- added this in this in the branch `feat/hp/room2`

2021-08-12 15:50 UTC, closed without merging